// Generated by tools/scripts/generate-web-runtime.mjs (env: development)
export const webRuntime = {
  "surface": "admin-moderation",
  "containerRole": "microfrontend",
  "phase": "mock",
  "serviceMode": "mock",
  "apiBaseUrls": {
    "auth": "http://localhost:8081",
    "content": "http://localhost:8082",
    "gamification": "http://localhost:8083",
    "leaderboard": "http://localhost:8084",
    "spacedRepetition": "http://localhost:8085"
  }
} as const;
