/*
  apps/web/website/src/main.tsx

  Website host container.
  - Purpose: act as the learner-facing host that composes multiple website microfrontends.
  - Composition style: mounts MFEs via `iframe` during local development. Each MFE
    runs on its own dev server/port (see websiteFeatures list below).
  - When tracing the codebase: read `runtime.generated.ts` first to understand the
    configured `webRuntime` environment, then this host, then the target MFE's
    `src/main.tsx` to inspect feature implementation.
*/
import { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { create } from 'zustand';
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@code-quest/shared-ui';
import { webRuntime } from './runtime.generated';

// Normalise the runtime phase to a string so entrypoints can compare reliably.
// The `webRuntime` object is generated by `tools/scripts/generate-web-runtime.mjs`.
// It reflects whether we're running with `development`, `production`, or local
// mock modes (e.g. 'mock', 'api-mock'). Update by re-running the prepare script.
const runtimePhase = String(webRuntime.phase);

// A union type for the website microfrontends. Each MFE is served independently
// during local development and mounted into this host via an iframe.
type WebsiteFeature = 'learning-path' | 'lessons' | 'hearts-gems' | 'league-social' | 'profile-settings';

interface WebsiteState {
  // Currently selected MFE to display in the host.
  activeFeature: WebsiteFeature;
  // Setter used by host UI controls to switch the mounted MFE.
  setFeature: (feature: WebsiteFeature) => void;
}

// Lightweight local store so the host UI can switch which iframe is mounted.
// We use `zustand` here for a minimal footprint; this is intentionally simple
// because the hosts shouldn't hold heavy application state - MFEs own their state.
const useWebsiteStore = create<WebsiteState>((set) => ({
  activeFeature: 'learning-path',
  setFeature: (activeFeature) => set({ activeFeature }),
}));

// Human-readable label for the current environment mode shown in the host UI.
// Useful to quickly see whether the host is wired to real APIs or using mocks.
const sourceLabel =
  runtimePhase === 'mock'
    ? 'frontend mock data'
    : runtimePhase === 'api-mock'
      ? 'frontend + API mock'
      : 'frontend + API + database';

// Registry of website MFEs the host can mount. During local development each
// entry points to a dev server running separately (see the `url` ports).
// In production these would be replaced by the deployed MFE host locations.
const websiteFeatures: Array<{ id: WebsiteFeature; label: string; description: string; url: string }> = [
  {
    id: 'learning-path',
    label: 'Learning Path',
    description: 'Guided path map and progression checkpoints.',
    url: 'http://localhost:4210',
  },
  {
    id: 'lessons',
    label: 'Lessons',
    description: 'Lesson player and practice sessions.',
    url: 'http://localhost:4211',
  },
  {
    id: 'hearts-gems',
    label: 'Hearts & Gems',
    description: 'Lives and premium currency interaction surface.',
    url: 'http://localhost:4212',
  },
  {
    id: 'league-social',
    label: 'League & Social',
    description: 'Leagues, leaderboards, and social feed touchpoints.',
    url: 'http://localhost:4213',
  },
  {
    id: 'profile-settings',
    label: 'Profile & Settings',
    description: 'Profile, account preferences, and personalization.',
    url: 'http://localhost:4214',
  },
];

function WebsiteApp() {
  const { activeFeature, setFeature } = useWebsiteStore();
  const currentFeature = useMemo(
    () => websiteFeatures.find((feature) => feature.id === activeFeature) ?? websiteFeatures[0],
    [activeFeature]
  );

  return (
    <main
      style={{
        minHeight: '100vh',
        padding: 24,
        background:
          'radial-gradient(circle at top, rgba(59, 130, 246, 0.18), transparent 32%), linear-gradient(180deg, #08111f 0%, #0f172a 100%)',
        color: '#e2e8f0',
        fontFamily:
          'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      }}
    >
      <div style={{ margin: '0 auto', maxWidth: 1160 }}>
        <Card>
          <CardHeader>
            <Badge tone="default">Website host</Badge>
            <div style={{ height: 12 }} />
            <CardTitle>Code Quest Website</CardTitle>
            <CardDescription>
              Learner host container composing multiple website microfrontends.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div style={{ display: 'grid', gap: 8, marginBottom: 16 }}>
              <Badge tone="success">{sourceLabel}</Badge>
              <div style={{ color: '#94a3b8', fontSize: 13, lineHeight: 1.6 }}>
                  {/* Quick runtime info: surface/containerRole/serviceMode come from runtime.generated.ts */}
                  surface: {webRuntime.surface} | container: {webRuntime.containerRole} | service mode: {webRuntime.serviceMode}
                </div>
            </div>
            <div
              style={{
                display: 'grid',
                gap: 12,
                gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              }}
            >
              {websiteFeatures.map((feature) => (
                <Button
                  key={feature.id}
                  variant={feature.id === activeFeature ? 'default' : 'secondary'}
                  onClick={() => setFeature(feature.id)}
                >
                  {feature.label}
                </Button>
              ))}
            </div>
          </CardContent>
        </Card>

        <div style={{ height: 24 }} />

        <div
          style={{
            display: 'grid',
            gap: 24,
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          }}
        >
          <Card>
            <CardHeader>
              <Badge tone="success">Composed feature</Badge>
              <div style={{ height: 12 }} />
              <CardTitle>{currentFeature.label}</CardTitle>
              <CardDescription>{currentFeature.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <div style={{ color: '#94a3b8', fontSize: 14, lineHeight: 1.7 }}>
                The selected website MFE is mounted below via runtime URL mapping.
                {/* Note: ensure you run `npm run prepare:web-runtime:dev` before serving
                    so `runtime.generated.ts` is present and correctly configured. */}
              </div>
              <div style={{ height: 12 }} />
              <div style={{ color: '#94a3b8', fontSize: 13 }}>
                endpoint: {currentFeature.url}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Badge tone="outline">Mounted MFE</Badge>
              <div style={{ height: 12 }} />
              <CardTitle>{currentFeature.label}</CardTitle>
              <CardDescription>Iframe host bridge for local composition.</CardDescription>
            </CardHeader>
            <CardContent>
              {/*
                Iframe composition for local development:
                - Each MFE runs its own dev server (different port). Host mounts it here.
                - For communication between host and MFE, use `window.postMessage` and
                  a small message bridge (not implemented here yet). Keep the bridge
                  minimal and well-scoped (navigation, auth token exchange, events).
                - Beware cross-origin restrictions if MFEs are hosted on different
                  origins; postMessage is the recommended safe way to communicate.
              */}
              <iframe
                key={currentFeature.id}
                title={`${currentFeature.id}-microfrontend`}
                src={currentFeature.url}
                style={{
                  width: '100%',
                  minHeight: 520,
                  border: '1px solid rgba(148, 163, 184, 0.28)',
                  borderRadius: 16,
                  backgroundColor: '#020617',
                }}
              />
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  );
}

const root = document.getElementById('root');

if (root) {
  createRoot(root).render(<WebsiteApp />);
}